language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: yuSaFeJeHOTMv4teCRc2B6dWcP/i/yIfAOzP9d5KdDOGDuEmjWT3bpndbZ8ToNgXdjwnX0JftW6a+xFdlTl8HqbOy17+8BXWRFLHqvlP5wnteOeZU8kbRmYFwkyD+ySsP+vKWgEsu0AW2b/HJ+M4znplgelwLnUo1MR/74fJlT1N9bpocP3LuZxCLASW1l7JN94UdLcqsRYy+I4h5noksoIM6JyiPhNOcJKpZaSYx6jjyxzWpmKPwMCVqkkvAIPCHsvc0BODi9N/pAamR/5jB3BMBbjThnWA0c+FOLq1+9UNnccE8ToKoAkSM4WcrngFmhlIC8qeNF4csa8var1j+R3jrtopYe8DzGVGQE1Px0Tiu++0bKZumV9Uo2YukF12K4UTEc7nv/oY/q1eQPB7ue3j3WxAb+z7pZvys4SqiSxLJuZR7WyiRSfmgm5fjz3Ay2LSQwaMEjPPkf5djYrKaiNu7KTHcsI7WtIZcxD7BCcqIvkH45NUFP6i7ihZwnn8txqFzACvXO7dNTmaDsjzwuQscEj+n+ubQnASyc5nSs3LObCpsExBmFAJcCx22TdTEE/Rr+/3gFtFgN4/Q7wIsNbn3tp+5WfuPfyMKq07He37x+hL4MepjuZDBZUy0QP7pLJOEdtvHkwqKIqJW0bxXz7gQ8UaPF/SR8hcy+aV7uM=
  app: dumnex-tratamiento
